# Generated by Django 3.2.9 on 2021-11-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='location',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='culture',
            name='picture',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='culture',
            name='type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
