# Generated by Django 3.2.9 on 2021-11-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211123_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='history',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='culture',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='culture',
            name='picture',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='culture',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
