# Generated by Django 3.2.9 on 2021-12-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_culture_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='culture',
            old_name='location',
            new_name='lat',
        ),
        migrations.AddField(
            model_name='culture',
            name='lng',
            field=models.CharField(default='', max_length=50),
        ),
    ]
