# Generated by Django 3.2.9 on 2021-12-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211203_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='location',
        ),
        migrations.AddField(
            model_name='city',
            name='lat',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='city',
            name='lng',
            field=models.CharField(default='', max_length=50),
        ),
    ]
