# Generated by Django 3.2.9 on 2021-12-03 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211203_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='city',
            name='lng',
        ),
    ]
